### ISSUE TITLE
Fakegato Feature 

### ISSUE THREAD

**Issue by Krocko** [SeydX/homebridge-tado-thermostat#2]
Is it possible for you to add the fakegato feature?

**Comment by seydx** [comment]
Fakegato feature would be very nice, but i am new in coding plugins for homebridge and i am not the best coder :D but i will take a look, maybe in the next releases

**Comment by seydx** [comment]
**v1.2.0** is out, please update to latest version for **fakegato**.

`sudo npm install -g homebridge-tado-thermostat-plugin@latest`
