### ISSUE TITLE
Error after update to 1. 2. 4

### ISSUE THREAD

**Issue by det-box** [SeydX/homebridge-tado-thermostat#3]
Hi,
this Error:
![error](https://user-images.githubusercontent.com/8150405/36642721-9a9b10fc-1a3b-11e8-93fd-dfc48bddca0f.JPG)

go back to 1. 2. 0

**Comment by seydx** [comment]
should be fixed with https://github.com/SeydX/homebridge-tado-thermostat/commit/4c63cf34a79aabfc29aabcc132516ef982ac2243 , https://github.com/SeydX/homebridge-tado-thermostat/commit/3adf8e7d72d454f514eb3a13f57c58c20619b071

can you try with the latest version @det-box

**Comment by det-box** [comment]
Is fixed with 1. 2. 5
no Errors.

Thank you

**Comment by seydx** [comment]
im glad to help you :)
