### ISSUE TITLE
Question: what kind of physical bridge?

### ISSUE THREAD

**Issue by QHose** [SeydX/homebridge-tado-thermostat#5]
Hi, sorry for asking I do see it anywhere mentioned. But do I also need a physical bridge? (I now have Philips hue v2 bridge) or only just homebridge? Thanks a lot!

**Comment by QHose** [comment]
(I want to buy a couple of Tado thermostats, and I wonder if I need the Tado bridge as well, because that one itself already has HomeKit support, so then why this project)

**Comment by seydx** [comment]
Hey

For remote access you will need the bridge. The difference between the bridge and this plugin is:

The tado bridge exposes the thermostats with just this functions:

- Thermostat with 2 modes (on and off)
- Built-in humidity sensor

And here a few things that my plugin exposes to HomeKit:

- 4 modes (off, heat, cool and automatic)
- Built-in humidity sensor
- Built-in battery state with low battery notification
- Delay Timer
- One Switch to controll all thermostats together (on/off)
- Exposes Hot Water boiler to HomeKit
- Exposes the window detection as contact sensors to homekit
- Exposes occupancy sensors to HomeKit
- Exposes "Anyone" sensor to HomeKit
- Exposes weather temperature sensor to HomeKit (also supports openweather for more details like airpressure, humidity etc)
- Elgato History function (see images for more details)
- Full Siri integration

And more functions are coming :)

**Comment by QHose** [comment]
wow so cool! thanks alot

**Comment by seydx** [comment]
:)
