### ISSUE TITLE
401 - authentication error

### ISSUE THREAD

**Issue by oynek** [SeydX/homebridge-tado-thermostat#6]
Installations worked like a charm. But the plugin fails to retrieve tado information. Seems to be an authentication error. Checked my credentials twice - they are correct. Might be a problem with special characters: I use a "&"-sign in my tado-password. Had similar issues with other plugins.

```
[2018-3-26 12:41:23] [Thermostat] Getting HomeID...                                                           
[2018-3-26 12:41:23] [Thermostat] HomeID Error: Error: Failed to load data, status code: 401
```

btw: Where can i find HomeID manually?

**Comment by seydx** [comment]
Set homeID manually will not fix the problem because i.e. requesting the state will also need credentials

I will test transforming the credentials and try to fix that in the next version

**Comment by seydx** [comment]
v3.1.7 is up
Should be Fixed, can you try it pls

**Comment by oynek** [comment]
Perfect. Authentication succeeded. But probably found another issue. Will open a different issue for it.

**Comment by seydx** [comment]
Ok, im closing this issue then
