### ISSUE TITLE
Hot water current temperature

### ISSUE THREAD

**Issue by mylesagray** [SeydX/homebridge-tado-thermostat#8]
I realise this may just be a limitation of the Tado API (they might not actually expose the hot water's _actual_ temperature) but mine is always showing 55C when turned on and 0C when off.

I know OpenTherm supports this as my old digital boiler controller showed me actual HW tank temperature and Tado must be able to read this in order to actually heat to a specific temperature - but it doesn't seem to be working in my installation - always shows the set point.

Is there anything in the API that will allow you to read back _actual_ tank temperature and not just the set point?

**Comment by seydx** [comment]
The Tado API gives no Information about the Current water temperature

Setted temperature is = Current temperature

Outlook für iOS<https://aka.ms/o0ukef> beziehen
________________________________
