### ISSUE TITLE
FakeGato doesn’t work with ä, ö and ü in room name 

### ISSUE THREAD

**Issue by Heiliger85** [SeydX/homebridge-tado-thermostat#9]
Hey, 

Your plugin is nice and has a lot more functions. Including FakeGato.

I have a room with the name ‘Gästezimmer’, all my rooms show in the eve app, but this room have no history. After I have rename this room to ‘Gaestezimmer’ , I can see the history.

Thank you.

**Comment by seydx** [comment]
Yes its because fakegato doesnt publish history to eve with special characters like ä,ö,ü,/, etc

**Comment by Heiliger85** [comment]
Can you change the room name automatic, that’s easier for all users and makes possible to use ä, ö and ü in the official Tado app. 
After the import to HomeKit the user can change the room name manual.

Thank you
